name: Publish nuget package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build
    - name: Pack nuget package
      run: dotnet pack --output nupkgs
    - name: Push nuget package
      run: dotnet nuget push "**/nupkgs/*.nupkg" -k ${{secrets.NUGET_API_KEY}}  -s "https://www.nuget.org/"
